version: "3.8"
services:
  secret-santa-web:
    container_name: dev-secret-santa-web
    build: .
    networks:
      - santa_test_network
    restart: always
    volumes:
      - .:/usr/bin/secretsanta
    ports:
      - "9001:9000"
    environment:
      - APP_ROOT=/usr/bin/secretsanta
      - PORT=9000
      - DATABASE_URL=postgres://postgres@secret-santa-postgres:5432/postgres
      - MAIL_USERNAME=dev-username
      - MAIL_PASSWORD=dev-password
      - SECRET_KEY=hellosecretkey
      - ENV=development
      - CELERY_BROKER_URL=redis://secret-santa-redis
      - CELERY_RESULT_BACKEND=redis://secret-santa-redis
      - PYTHONPATH=.
    entrypoint: "./dev-entrypoint.sh"
  secret-santa-celery-service:
    container_name: dev-secret-santa-celery-service
    build: .
    networks:
      - santa_test_network
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - .:/usr/bin/secretsanta
    environment:
      - APP_ROOT=/usr/bin/secretsanta
      - DATABASE_URL=postgres://postgres@secret-santa-postgres:5432/postgres
      - ENV=development
      - CELERY_BROKER_URL=redis://secret-santa-redis
      - CELERY_RESULT_BACKEND=redis://secret-santa-redis
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - SENDGRID_INVITE_TEMPLATE_ID=${SENDGRID_INVITE_TEMPLATE_ID}
      - SENDGRID_PAIR_TEMPLATE_ID=${SENDGRID_PAIR_TEMPLATE_ID}
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - UID=5000
      - GID=5000
    entrypoint: "./celery-init.sh"
  secret-santa-redis:
    container_name: dev-secret-santa-redis
    networks:
      - santa_test_network
    image: redis
  secret-santa-postgres:
    container_name: dev-secret-santa-postgres
    networks:
      - santa_test_network
    image: postgres
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  santa_test_network:
    name: santa_test_network
    driver: bridge
