version: "3.8"
services:
  nginx:
    image: iamprithaj/nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "9000:80"
  secret-santa-web:
    image: iamprithaj/secret-santa-web
    restart: always
    build: .
    environment:
      - APP_ROOT=/usr/bin/secretsanta
      - PORT=9000
      - DATABASE_URL=postgres://postgres@secret-santa-postgres:5432/postgres
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - ENV=production
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_INVITE_TEMPLATE_ID=${SENDGRID_INVITE_TEMPLATE_ID}
      - SENDGRID_PAIR_TEMPLATE_ID=${SENDGRID_PAIR_TEMPLATE_ID}
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - CELERY_BROKER_URL=redis://secret-santa-redis
      - CELERY_RESULT_BACKEND=redis://secret-santa-redis
      - PYTHONPATH=.
    entrypoint: "./entrypoint.sh"
  secret-santa-celery-service:
    image: iamprithaj/secret-santa-celery-service
    restart: always
    build: .
    user: "${UID}:${GID}"
    environment:
      - APP_ROOT=/usr/bin/secretsanta
      - DATABASE_URL=postgres://postgres@secret-santa-postgres:5432/postgres
      - ENV=production
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_INVITE_TEMPLATE_ID=${SENDGRID_INVITE_TEMPLATE_ID}
      - SENDGRID_PAIR_TEMPLATE_ID=${SENDGRID_PAIR_TEMPLATE_ID}
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - CELERY_BROKER_URL=redis://secret-santa-redis
      - CELERY_RESULT_BACKEND=redis://secret-santa-redis
      - UID=5000
      - GID=5000
    entrypoint: "./celery-init.sh"
  secret-santa-redis:
    image: redis
    restart: always
  secret-santa-postgres:
    volumes:
      - /home/ubuntu/.local/volumes/my-secret-santa:/var/lib/postgresql/data
    image: postgres
    restart: always
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust 