"""make hint a text field

Revision ID: 05d3bcc394b7
Revises: b5123cfd3cc9
Create Date: 2024-12-10 22:23:49.020284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d3bcc394b7'
down_revision = 'b5123cfd3cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hint',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hint',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
