"""empty message

Revision ID: 150015ed75c9
Revises: 8e1d591d9ac8
Create Date: 2021-10-23 19:54:44.727098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150015ed75c9'
down_revision = '8e1d591d9ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_invites', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('email_invites', sa.Column('payload', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'email_invites', ['code'])
    op.drop_constraint('email_invites_group_id_fkey', 'email_invites', type_='foreignkey')
    op.drop_column('email_invites', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_invites', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('email_invites_group_id_fkey', 'email_invites', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'email_invites', type_='unique')
    op.drop_column('email_invites', 'payload')
    op.drop_column('email_invites', 'code')
    # ### end Alembic commands ###
