"""empty message

Revision ID: 193966496a6b
Revises: 346520f237e9
Create Date: 2021-11-10 08:20:05.390640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193966496a6b'
down_revision = '346520f237e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logged_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logged_in')
    # ### end Alembic commands ###
