"""empty message

Revision ID: 233a14d89aab
Revises: 447e46d97ff1
Create Date: 2020-10-10 13:38:35.134190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233a14d89aab'
down_revision = '447e46d97ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='participants_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participants_pkey'),
    sa.UniqueConstraint('email', name='participants_email_key'),
    sa.UniqueConstraint('user_id', name='participants_user_id_key')
    )
    # ### end Alembic commands ###
