"""empty message

Revision ID: 38544e4f4097
Revises: 233a14d89aab
Create Date: 2020-10-10 14:04:21.042808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38544e4f4097'
down_revision = '233a14d89aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
