"""add created_at to groups

Revision ID: 3e5b15d3603c
Revises: e0baa224a33b
Create Date: 2023-11-20 22:35:35.887809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e5b15d3603c"
down_revision = "e0baa224a33b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute(
        """
        UPDATE groups set created_at='2023-10-01'::date WHERE created_at is null;
        """
    )
    op.alter_column("groups", "created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "created_at")
    # ### end Alembic commands ###
