"""empty message

Revision ID: 7ca5d5ef746f
Revises: 9ddb12d026c3
Create Date: 2019-11-22 23:15:49.160353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca5d5ef746f'
down_revision = '9ddb12d026c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
