"""empty message

Revision ID: 84b4464ccb56
Revises: 193966496a6b
Create Date: 2021-11-10 08:28:29.609864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b4464ccb56'
down_revision = '193966496a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logged_out', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logged_out')
    # ### end Alembic commands ###
