"""empty message

Revision ID: 8b1a156f0f67
Revises: d160c45e1035
Create Date: 2020-11-15 15:52:38.712736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b1a156f0f67"
down_revision = "d160c45e1035"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("hint", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hint")
    op.drop_column("users", "address")
    # ### end Alembic commands ###
