"""empty message

Revision ID: 970e2cc278e3
Revises: 8a6a57b41c80
Create Date: 2018-11-03 10:50:21.289506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970e2cc278e3'
down_revision = '8a6a57b41c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('participants', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('participants', 'first_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('participants', 'hint',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('participants', 'last_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'last_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('participants', 'hint',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('participants', 'first_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('participants', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('participants', 'address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
