"""empty message

Revision ID: 9ddb12d026c3
Revises: 58369623e2dc
Create Date: 2019-11-22 22:01:09.173384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddb12d026c3'
down_revision = '58369623e2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'password')
    # ### end Alembic commands ###
