"""add updated_at to groups

Revision ID: a780518fabf9
Revises: 3e5b15d3603c
Create Date: 2023-11-20 22:43:51.796029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a780518fabf9'
down_revision = '3e5b15d3603c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'updated_at')
    # ### end Alembic commands ###
