"""empty message

Revision ID: c742dae2f273
Revises: 2b86987c2a68
Create Date: 2020-12-17 06:18:52.859429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c742dae2f273"
down_revision = "2b86987c2a68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_invites",
        "timestamp",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "pairs",
        "timestamp",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pairs",
        "timestamp",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "email_invites",
        "timestamp",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
