"""empty message

Revision ID: d160c45e1035
Revises: d0c52114eb3d
Create Date: 2020-11-07 06:04:51.805061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160c45e1035'
down_revision = 'd0c52114eb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups_and_users', sa.Column('participating', sa.Boolean(), nullable=True))
    op.add_column('pairs', sa.Column('emailed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'emailed')
    op.drop_column('groups_and_users', 'participating')
    # ### end Alembic commands ###
