"""empty message

Revision ID: e0baa224a33b
Revises: bae2f6c1034e
Create Date: 2023-10-17 12:56:14.495785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0baa224a33b'
down_revision = 'bae2f6c1034e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.Enum('GOOGLE', 'GITHUB', 'GITLAB', name='oauthproviderenum'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth_profiles')
    # ### end Alembic commands ###
