"""empty message

Revision ID: ec6568a03afa
Revises: ece209297acb
Create Date: 2021-09-13 11:32:55.307272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6568a03afa'
down_revision = 'ece209297acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###
