"""empty message

Revision ID: edfad35c2de6
Revises: 53e5c0498957
Create Date: 2020-12-26 07:57:25.336764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edfad35c2de6"
down_revision = "53e5c0498957"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_pair_reveals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "groups", sa.Column("reveal_latest_pairs", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "reveal_latest_pairs")
    op.drop_table("group_pair_reveals")
    # ### end Alembic commands ###
