name: Secret Santa Image Build/Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_container_image:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      SENDGRID_INVITE_TEMPLATE_ID: ${{ secrets.SENDGRID_INVITE_TEMPLATE_ID }}
      SENDGRID_PAIR_TEMPLATE_ID: ${{ secrets.SENDGRID_PAIR_TEMPLATE_ID }}
      SENDGRID_RESET_PASSWORD_TEMPLATE_ID: ${{ secrets.SENDGRID_RESET_PASSWORD_TEMPLATE_ID }}
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - run: ./jobs/build_container_image.sh 

  deploy_all_services:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      SENDGRID_INVITE_TEMPLATE_ID: ${{ secrets.SENDGRID_INVITE_TEMPLATE_ID }}
      SENDGRID_PAIR_TEMPLATE_ID: ${{ secrets.SENDGRID_PAIR_TEMPLATE_ID }}
      SENDGRID_RESET_PASSWORD_TEMPLATE_ID: ${{ secrets.SENDGRID_RESET_PASSWORD_TEMPLATE_ID }}
    needs: build_container_image
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - run: ./jobs/deploy_all_services.sh

  
